ecomapp/urls.py
from django.urls import path
from ecomapp.views import (HomePageView, AboutPageView, ContactPageView, BasePage,
                        AllProductView,ProductDetailView,AddToCart,MyCart,ManageCartView)

app_name = "ecomapp"

urlpatterns = [
    path("base/", BasePage.as_view(), name="base_page"),
    path("about/", AboutPageView.as_view(), name="about_page"),
    path("contact/", ContactPageView.as_view(), name="contact_us"),
    path("", HomePageView.as_view(), name="home_page"),

    path("all-product/", AllProductView.as_view(), name="all_product_view"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product_detail_view"),
    path("add-to-cart/<int:pro_id>/", AddToCart.as_view(), name="add_to_cart"),
    path('my-cart/', MyCart.as_view(), name="my_cart"),
    path("manage-cart/<int:object_id>/", ManageCartView.as_view(), name="manage_cart")

]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class DateTimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        abstract = True


class Customer(DateTimeStamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="customers")
    full_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return "{}".format(self.full_name)


class Category(DateTimeStamp):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering=('-created_at',)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return "{}".format(self.title)

class Product(DateTimeStamp):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images", blank=True, null=True)
    marked_price = models.PositiveIntegerField(default=0, blank=True,null=True)
    selling_price = models.PositiveIntegerField(default=0, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    warranty = models.CharField(max_length=100, null=True, blank=True)
    return_policy = models.CharField(max_length=100, blank=True, null=True)
    view_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return "{}".format(self.title)



class Cart(DateTimeStamp):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    
    class Meta:
        ordering = ('-created_at',)
        verbose_name = "Cart"
        verbose_name_plural = "Carts"

    def __str__(self):
        return "Cart: "+str(self.id)

class CartProduct(DateTimeStamp):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    sub_total = models.PositiveIntegerField()

    class Meta:
        ordering = ('-created_at',)
        verbose_name = "CartProduct"
        verbose_name_plural = "CartProducts"

    def __str__(self):
        return "Cart: "+str(self.id) + "CartProduct: "+str(self.id)


ORDER_STATUS = (
    ("Order Received","Order Received"),
    ("Order Processing","Order Processing"),
    ("On the Way","On the way"),
    ("Order Completed","Order Completed"),
    ("Order Canceled","Order Canceled")
)

class Order(DateTimeStamp):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=100)
    shipping_address = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    sub_total = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=100, choices=ORDER_STATUS)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def __str__(self):
        return "Cart: "+str(self.id)

ecomapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, View
from ecomapp.models import Product, Category, Cart, CartProduct
# Create your views here.

class BasePage(TemplateView):
    template_name = "ecomapp/base.html"

class HomePageView(TemplateView):
    template_name = "ecomapp/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["product_list"] = Product.objects.all()
        return context

class AboutPageView(TemplateView):
    template_name = "ecomapp/about.html"


class ContactPageView(TemplateView):
    template_name = "ecomapp/contact_us.html"
    

class AllProductView(TemplateView):
    template_name = "ecomapp/allproduct.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_categories'] = Category.objects.all()
        return context


class ProductDetailView(TemplateView):
    template_name = "ecomapp/product_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        product = Product.objects.get(slug=url_slug)
        product.view_count += 1
        product.save()
        context['product'] = product
        return context


class AddToCart(TemplateView):
    template_name = "ecomapp/add_to_cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #get product id from requested url
        product_id = self.kwargs['pro_id']
       
        product_object = Product.objects.get(id=product_id)
        

        #now checking the session if the cart is exists or not
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(
                product = product_object
            )
            #item already exists in cart
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.sub_total += product_object.selling_price
                cartproduct.save()
                cart_obj.total += product_object.selling_price
                cart_obj.save()
            #new items in added in cart
            else:
                cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_object,
                    rate=product_object.selling_price,
                    quantity=1, sub_total=product_object.selling_price
                )
                cart_obj.total += product_object.selling_price
                cart_obj.save()
        else:
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_object,
                    rate=product_object.selling_price,
                    quantity=1, sub_total=product_object.selling_price
                )
            cart_obj.total += product_object.selling_price
            cart_obj.save()
        return context


class MyCart(TemplateView):
    template_name = "ecomapp/my_cart.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context["cart"] = cart
        return context

class ManageCartView(View):
    def get(self, request, *args, **kwargs):
        object_id = self.kwargs['object_id']
        action = request.GET.get("action")
        object_id = CartProduct.objects.get(id=object_id)
        cart_object = object_id.cart
        if action == "inc":
            object_id.quantity += 1
            object_id.sub_total += object_id.rate
            object_id.save()
            cart_object.total += object_id.rate
            cart_object.save()
        elif action == "dcr":
            object_id.quantity -= 1
            object_id.sub_total += object_id.rate
            object_id.save()
            cart_object.total += object_id.rate
            cart_object.save()
            if object_id.quantity == 0:
                object_id.delete()
        elif action == "rmv":
            cart_object.total -=  object_id.sub_total
            cart_object.save()
            object_id.delete()
        else:
            pass
        return redirect("ecomapp:my_cart")

ecomapp/templates/ecomapp/about.html
{% extends 'ecomapp/base.html' %}
{% block content %}
<h1> This is about Page</h1>

{% endblock %}

ecomapp/templates/ecomapp/add_to_cart.html
{% extends 'ecomapp/base.html' %}
{% block content %}
<div class="container">
    <h1> Product Add To Cart Successfully</h1>
</div>
{% endblock content %}

ecomapp/templates/ecomapp/allproduct.html
{% extends 'ecomapp/base.html' %}
{% block title %} All Product {% endblock title %}
{% block content %}
<div class="container">
    <h3> All Products </h3><hr>
    {% for object in all_categories %}
    <h1>{{ object.title }}</h1>
    <div class="row">
        {% for category in object.product_set.all %}
        <div class="col-md-3">
            <div class="m-4">
                <a href="{% url 'ecomapp:product_detail_view' category.slug %}"><h3>{{category.title}}</h3></a>
                {% if category.image %}
                <img src="{{category.image.url}}" alt="" class="img-fluid" style="height:250px; width:250px; object-fit:contain;">
                {% endif %}
                <p class="mt-3">Price: <strike>Rs: {{category.marked_price}}</strike> Rs: {{category.selling_price}}</p>
                <a href="{% url 'ecomapp:add_to_cart' category.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}

    </div>
    {% endfor %}
</div>
{% endblock %}

ecomapp/templates/ecomapp/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    {% block css %}
    {% endblock css %}
</head>

<body>
    {% include 'ecomapp/navbar.html' %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    {% block script %}
    {% endblock script %}
</body>

</html>

ecomapp/templates/ecomapp/contact_us.html
{% extends 'ecomapp/home.html' %}
{% block content %}
<h1> This is contact Page</h1>
{% endblock %}

ecomapp/templates/ecomapp/home.html
{% extends 'ecomapp/base.html' %}
{% block content %}
<div class="container">
    <h1 class="text-center"> Welcome to Ecommerce Website</h1>
    <div class="row mt-3">
        {% for object in product_list %}
        <div class="col-md-3">
            <div class="m-3">
                <h3>{{object.title}}</h3>
                {% if object.image %}
                <img src="{{object.image.url}}" alt="" class="img-fluid" style="height:250px; width:250px; object-fit:contain;">
                {% endif %}
                <p class="mt-3">Price: <strike>Rs: {{object.marked_price}}</strike> Rs: {{object.selling_price}}</p>
                <a href="{% url 'ecomapp:add_to_cart' object.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecomapp/templates/ecomapp/my_cart.html
{% extends 'ecomapp/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4> Item in my Cart </h4>
            <table class="table">
                <thead>
                    <tr>
                        <th> SN </th>
                        <th> Product </th>
                        <th> Rate </th>
                        <th> Quantity </th>
                        <th> SubTotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ object.product }}</td>
                        <td>{{ object.rate }}</td>
                        <td>{{ object.quantity }}</td>
                        <td>{{ object.sub_total }}</td>
                        <td>
                            <a href="{% url 'ecomapp:manage_cart' object.id %}?action=inc" class="btn btn-sm btn-primary"> + </a>
                            <a href="{% url 'ecomapp:manage_cart' object.id %}?action=dcr" class="btn btn-sm btn-warning"> - </a>
                            <a href="{% url 'ecomapp:manage_cart' object.id %}?action=rmv" class="btn btn-sm btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs: {{ cart.total }}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        
    </div>
</div>
{% endblock content %}

ecomapp/templates/ecomapp/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'ecomapp:home_page' %}">Home</a>
          <a class="nav-link" href="{% url 'ecomapp:about_page' %}">About</a>
          <a class="nav-link" href="{% url 'ecomapp:contact_us' %}">Contact Us</a>
          <a class="nav-link" href="{% url 'ecomapp:all_product_view' %}">All Product</a>
          <a class="nav-link" href="{% url 'ecomapp:my_cart' %}"> My Cart </a>
        </div>
      </div>
    </div>
  </nav>

ecomapp/templates/ecomapp/product_detail.html
{% extends 'ecomapp/base.html' %}
{% block title %} Product Detail {% endblock title %}
{% block content %}
<div class="container">
    <h1> Product: {{ product.title }}</h1>
    <div class="row">
        <div class="col-md-6">
            {% if product.image %}
            <img src="{{product.image.url}}" alt="" class="img-fluid" style="height:300px; width:400px; object-fit:contain;">
            {% endif %}
        </div>
        <div class="col-md-6">
            <h4>Product: {{ product.title }} (View {{product.view_count}} times)</h4>
            <h4>Category: {{ product.category }} </h4>
            <h4>Price: <strike>{{ product.marked_price }}</strike> {{ product.selling_price }}</h4>
            <a href="{% url 'ecomapp:add_to_cart' product.id %}" class="btn btn-sm btn-primary"> Add To Cart</a>
            <hr>
            <p class="text-info">Warranty: {{ product.warranty }}</p>
            <p class="text-info">Return Policy: {{ product.return_policy }}</p>
            <p>{{ product.description }}</p>
        </div>
    </div>
</div>
{% endblock content %}